export { default as Error } from './Error'
export { default as Login } from './Login/Login'
export { default as Registration } from './Registration/Registration'
export { default as Home } from './Home/Home'
export { default as Profile } from './Profile/Profile'
export { default as Chat } from './Chat/Chat'

export * from './Error'
export * from './Login/Login'
export * from './Registration/Registration'
export * from './Profile/Profile'
export * from './Home/Home'
export * from './Chat/Chat'
